//go:build ignore
// +build ignore

package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func main() {
	csvPath := flag.String("csv", "pfc_primary.csv", "path to taxonomy csv")
	outPath := flag.String("out", "primary.go", "output file")
	flag.Parse()

	records, err := readCSV(*csvPath)
	if err != nil {
		fail(err)
	}

	primaries := uniquePrimary(records)
	if err := writePrimary(*outPath, primaries); err != nil {
		fail(err)
	}
}

func readCSV(path string) ([][]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1
	return r.ReadAll()
}

func uniquePrimary(records [][]string) []string {
	seen := map[string]struct{}{}
	var primaries []string
	for i, row := range records {
		if i == 0 {
			continue
		}
		if len(row) == 0 {
			continue
		}
		primary := strings.TrimSpace(row[0])
		if primary == "" {
			continue
		}
		if _, ok := seen[primary]; ok {
			continue
		}
		seen[primary] = struct{}{}
		primaries = append(primaries, primary)
	}
	return primaries
}

func writePrimary(path string, primaries []string) error {
	outDir := filepath.Dir(path)
	if outDir != "." {
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	tmpl, err := template.New("primary").Parse(primaryTemplate)
	if err != nil {
		return err
	}

	data := struct {
		Primaries []string
	}{
		Primaries: primaries,
	}

	return tmpl.Execute(f, data)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

const primaryTemplate = `// Code generated by gen_primary.go; DO NOT EDIT.
package taxonomy

//go:generate go run gen_primary.go -csv pfc_primary.csv -out primary.go

var PFCPrimaryList = []string{
{{- range .Primaries }}
	"{{ . }}",
{{- end }}
}

var PFCPrimarySet = map[string]struct{}{
{{- range .Primaries }}
	"{{ . }}": {},
{{- end }}
}

func IsPFCPrimaryAllowed(primary string) bool {
	_, ok := PFCPrimarySet[primary]
	return ok
}
`
