// Code generated by gen_primary.go; DO NOT EDIT.
package taxonomy

//go:generate go run gen_primary.go -csv pfc_primary.csv -out primary.go

var PFCPrimaryList = []string{
	"INCOME",
	"TRANSFER_IN",
	"TRANSFER_OUT",
	"LOAN_PAYMENTS",
	"BANK_FEES",
	"ENTERTAINMENT",
	"FOOD_AND_DRINK",
	"GENERAL_MERCHANDISE",
	"HOME_IMPROVEMENT",
	"MEDICAL",
	"PERSONAL_CARE",
	"GENERAL_SERVICES",
	"GOVERNMENT_AND_NON_PROFIT",
	"TRANSPORTATION",
	"TRAVEL",
	"RENT_AND_UTILITIES",
}

var PFCPrimarySet = map[string]struct{}{
	"INCOME": {},
	"TRANSFER_IN": {},
	"TRANSFER_OUT": {},
	"LOAN_PAYMENTS": {},
	"BANK_FEES": {},
	"ENTERTAINMENT": {},
	"FOOD_AND_DRINK": {},
	"GENERAL_MERCHANDISE": {},
	"HOME_IMPROVEMENT": {},
	"MEDICAL": {},
	"PERSONAL_CARE": {},
	"GENERAL_SERVICES": {},
	"GOVERNMENT_AND_NON_PROFIT": {},
	"TRANSPORTATION": {},
	"TRAVEL": {},
	"RENT_AND_UTILITIES": {},
}

func IsPFCPrimaryAllowed(primary string) bool {
	_, ok := PFCPrimarySet[primary]
	return ok
}
