// Code generated by gen_primary.go; DO NOT EDIT.
package taxonomy

//go:generate go run gen_primary.go -csv pfc_primary.csv -out primary.go

var PFCPrimaryList = []string{
	"INCOME",
	"LOAN_DISBURSEMENTS",
	"TAX_REFUND",
	"INTERESTS_AND_DIVIDENDS",
	"TRANSFER_IN",
	"TRANSFER_OUT",
	"LOAN_PAYMENTS",
	"BANK_FEES",
	"BANK_PENALTIES",
	"INTEREST_PAYMENTS",
	"ENTERTAINMENT",
	"DINING",
	"FOOD_RETAIL",
	"GENERAL_MERCHANDISE",
	"MEDICAL",
	"PERSONAL_CARE",
	"PET_CARE_AND_SUPPLIES",
	"CHILDCARE_AND_EDUCATION",
	"GENERAL_SERVICES",
	"GOVERNMENTS_AND_NON_PROFIT",
	"TRAVEL_AND_TRANSPORTATION",
	"RENT_AND_UTILITIES",
	"INSURANCE_AND_TAX",
	"OTHER",
	"UNKNOWN",
}

var PFCPrimarySet = map[string]struct{}{
	"INCOME":                     {},
	"LOAN_DISBURSEMENTS":         {},
	"TAX_REFUND":                 {},
	"INTERESTS_AND_DIVIDENDS":    {},
	"TRANSFER_IN":                {},
	"TRANSFER_OUT":               {},
	"LOAN_PAYMENTS":              {},
	"BANK_FEES":                  {},
	"BANK_PENALTIES":             {},
	"INTEREST_PAYMENTS":          {},
	"ENTERTAINMENT":              {},
	"DINING":                     {},
	"FOOD_RETAIL":                {},
	"GENERAL_MERCHANDISE":        {},
	"MEDICAL":                    {},
	"PERSONAL_CARE":              {},
	"PET_CARE_AND_SUPPLIES":      {},
	"CHILDCARE_AND_EDUCATION":    {},
	"GENERAL_SERVICES":           {},
	"GOVERNMENTS_AND_NON_PROFIT": {},
	"TRAVEL_AND_TRANSPORTATION":  {},
	"RENT_AND_UTILITIES":         {},
	"INSURANCE_AND_TAX":          {},
	"OTHER":                      {},
	"UNKNOWN":                    {},
}

func IsPFCPrimaryAllowed(primary string) bool {
	_, ok := PFCPrimarySet[primary]
	return ok
}
