config:
  gcp:project: finance-app-dev-491520
  gcp:region: us-central1
  shared:stack: gregmsthompson/finance-shared/dev
  worker:stack: gregmsthompson/finance-worker/dev
  cloudrun:minScale: "0"
  cloudrun:maxScale: "1"
  cloudrun:cpu: "1"
  cloudrun:memory: 512Mi
  cloudrun:concurrency: "80"
  cloudrun:logLevel: debug
  cloudrun:timeout: "60"
  plaid:environment: sandbox
  vertex:model: gemini-2.5-flash-lite
  app:aiTtl: 168h
  plaid:webhookUrl: https://apiservice-48f351a-281388559735.us-central1.run.app/plaid/webhook
  plaid:appleAppId: 45W33LPJ2T.com.gregmsthompson.financeapp
